### ISSUE TITLE
First time docker run fails

### ISSUE THREAD

**Issue by JIOB** [maddox/harmony-api#25]
Just pulled and attempted to run your docker and it failed to run. Config folder remains empty. The docker log is below. Am i doing something wrong?

> npm info it worked if it ends with ok
> stderr
> 11:27:17
> npm info using npm@2.15.9
> stderr
> 11:27:17
> npm info using node@v4.6.0
> stderr
> 11:27:17
> npm info prestart harmony-api@2.0.0
> stderr
> 11:27:17
> npm info start harmony-api@2.0.0
> stderr
> 11:27:17
> stdout
> 11:27:17
> &gt; harmony-api@2.0.0 start /usr/src/app
> stdout
> 11:27:17
> &gt; node app.js
> stdout
> 11:27:17
> stdout
> 11:27:17
> module.js:327
> stderr
> 11:27:17
>     throw err;
> stderr
> 11:27:17
>     ^
> stderr
> 11:27:17
> stderr
> 11:27:17
> Error: Cannot find module '/config/config.json'
> stderr
> 11:27:17
>     at Function.Module._resolveFilename (module.js:325:15)
> stderr
> 11:27:17
>     at Function.Module._load (module.js:276:25)
> stderr
> 11:27:17
>     at Module.require (module.js:353:17)
> stderr
> 11:27:17
>     at require (internal/module.js:12:17)
> stderr
> 11:27:17
>     at Object.&lt;anonymous&gt; (/usr/src/app/app.js:11:14)
> stderr
> 11:27:17
>     at Module._compile (module.js:409:26)
> stderr
> 11:27:17
>     at Object.Module._extensions..js (module.js:416:10)
> stderr
> 11:27:17
>     at Module.load (module.js:343:32)
> stderr
> 11:27:17
>     at Function.Module._load (module.js:300:12)
> stderr
> 11:27:17
>     at Function.Module.runMain (module.js:441:10)
> stderr
> 11:27:17
> stderr
> 11:27:17
> npm info harmony-api@2.0.0 Failed to exec start script
> stderr
> 11:27:17
> npm ERR! Linux 3.10.35
> stderr
> 11:27:17
> npm ERR! argv &quot;/usr/local/bin/node&quot; &quot;/usr/local/bin/npm&quot; &quot;start&quot;
> stderr
> 11:27:17
> npm ERR! node v4.6.0
> stderr
> 11:27:17
> npm ERR! npm  v2.15.9
> stderr
> 11:27:17
> npm ERR! code ELIFECYCLE
> stderr
> 11:27:17
> npm ERR! harmony-api@2.0.0 start: `node app.js`
> stderr
> 11:27:17
> npm ERR! Exit status 1
> stderr
> 11:27:17
> npm ERR! 
> stderr
> 11:27:17
> npm ERR! Failed at the harmony-api@2.0.0 start script 'node app.js'.
> stderr
> 11:27:17
> npm ERR! This is most likely a problem with the harmony-api package,
> stderr
> 11:27:17
> npm ERR! not with npm itself.
> stderr
> 11:27:17
> npm ERR! Tell the author that this fails on your system:
> stderr
> 11:27:17
> npm ERR!     node app.js
> stderr
> 11:27:17
> npm ERR! You can get information on how to open an issue for this project with:
> stderr
> 11:27:17
> npm ERR!     npm bugs harmony-api
> stderr
> 11:27:17
> npm ERR! Or if that isn't available, you can get their info via:
> stderr
> 11:27:17
> npm ERR! 
> stderr
> 11:27:17
> npm ERR!     npm owner ls harmony-api
> stderr
> 11:27:17
> npm ERR! There is likely additional logging output above.
> stderr
> 11:27:17
> stderr
> 11:27:18
> npm ERR! Please include the following file with any support request:
> stderr
> 11:27:18
> npm ERR!     /usr/src/app/npm-debug.log

**Comment by JIOB** [comment]
I jumped the gun a little here Maddox, i hadn't added the config.json sample.

Thanks for your great work!
