### ISSUE TITLE
2.1 broken with fresh deps

### ISSUE THREAD

**Issue by maddox** [maddox/harmony-api#32]
After installing npm deps from scratch, it's suddenly doing this now:

```
Starting discovery.
Hub discovered: Bedroom at 192.168.1.109.
Hub discovered: Family Room at 192.168.1.106.
/Users/jmaddox/source/harmony-api/node_modules/harmonyhubjs-client/lib/login/hub.js:59
      if (response.identity && response.identity !== undefined) {
                  ^

TypeError: Cannot read property 'identity' of undefined
    at Client.<anonymous> (/Users/jmaddox/source/harmony-api/node_modules/harmonyhubjs-client/lib/login/hub.js:59:19)
    at emitOne (events.js:90:13)
    at Client.emit (events.js:182:7)
    at Client._handleStanza (/Users/jmaddox/source/harmony-api/node_modules/node-xmpp-client/lib/Client.js:227:12)
    at Client.onStanza (/Users/jmaddox/source/harmony-api/node_modules/node-xmpp-client/lib/Client.js:221:8)
    at emitOne (events.js:90:13)
    at Connection.emit (events.js:182:7)
    at Connection.onStanza (/Users/jmaddox/source/harmony-api/node_modules/node-xmpp-core/lib/Connection.js:377:10)
    at StreamParser.<anonymous> (/Users/jmaddox/source/harmony-api/node_modules/node-xmpp-core/lib/Connection.js:231:10)
    at emitOne (events.js:90:13)
```

**Comment by maddox** [comment]
https://github.com/swissmanu/harmonyhubjs-client/blob/v1.1.9/lib/login/hub.js#L59

**Comment by maddox** [comment]
```
Starting discovery.
Hub discovered: Bedroom at 192.168.1.109.
  harmonyhubjs:client:login login on hub 192.168.1.109 +0ms
  harmonyhubjs:client:login:hub perform hub login +0ms
  harmonyhubjs:client:login:hub retrieve identity by logging in as guest +1ms
Hub discovered: Family Room at 192.168.1.106.
  harmonyhubjs:client:login login on hub 192.168.1.106 +19ms
  harmonyhubjs:client:login:hub perform hub login +0ms
  harmonyhubjs:client:login:hub retrieve identity by logging in as guest +0ms
  harmonyhubjs:client:login:hub XMPP client connected +57ms
  harmonyhubjs:client:login:hub received XMPP stanza: <iq xmlns:stream="http://etherx.jabber.org/streams"/> +14ms
  harmonyhubjs:client:login:hub XMPP client connected +3ms
  harmonyhubjs:client:login:hub received XMPP stanza: <iq xmlns:stream="http://etherx.jabber.org/streams"/> +12ms
  harmonyhubjs:client:login:hub received XMPP stanza: <iq id="676771" to="guest" type="get" xmlns:stream="http://etherx.jabber.org/streams"><oa xmlns="connect.logitech.com" mime="vnd.logitech.connect/vnd.logitech.pair" errorcode="200" errorstring="OK"/></iq> +144ms
/Users/jmaddox/source/harmony-api/node_modules/harmonyhubjs-client/lib/login/hub.js:59
      if (response.identity && response.identity !== undefined) {
```

**Comment by jawilson** [comment]
Definitely a problem with a dependency. Looks like you created swissmanu/harmonyhubjs-client#28 already.

**Comment by maddox** [comment]
Yeah. I need to figure out what the old dep versions were and I could lock my fork to those and it might be fine.

**Comment by maddox** [comment]
OK, I got it working again. I locked `node-xmpp-client` in my fork of `harmonyhubjs-client` to `3.0.0` and its working again. Anything > `3.0.0` breaks.

You should be able wipe out your `node_modules` and reinstall them and it'll work fine.

**Comment by maddox** [comment]
This was fixed here: https://github.com/swissmanu/harmonyhubjs-client/pull/29

**Comment by maddox** [comment]
It was fixed the same way I fixed it on my fork, which is still locked to the project.

I'm going to close this now since it is in fact fixed, I'll move back to using the npm version soon.
