### ISSUE TITLE
TypeError during discovery

### ISSUE THREAD

**Issue by nkgilley** [maddox/harmony-api#34]
Running in Docker with host networking and I get this error during discovery:

``` bash
> harmony-api@2.1.0 start /usr/src/app
> node app.js

Starting discovery.
Hub discovered: Living Room at 192.168.1.147.
/usr/src/app/node_modules/harmonyhubjs-client/lib/login/hub.js:59
if (response.identity && response.identity !== undefined) {
^

TypeError: Cannot read property 'identity' of undefined
at Client.<anonymous> (/usr/src/app/node_modules/harmonyhubjs-client/lib/login/hub.js:59:19)
at emitOne (events.js:77:13)
at Client.emit (events.js:169:7)
at Client._handleStanza (/usr/src/app/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/lib/Client.js:227:12)
at Client.onStanza (/usr/src/app/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/lib/Client.js:221:8)
at emitOne (events.js:77:13)
at Connection.emit (events.js:169:7)
at Connection.onStanza (/usr/src/app/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:377:10)
at StreamParser.<anonymous> (/usr/src/app/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:231:10)
at emitOne (events.js:77:13)

npm info harmony-api@2.1.0 Failed to exec start script
```

**Comment by maddox** [comment]
be sure you `rm -Rf node_modules` and `npm install`  again.

**Comment by nkgilley** [comment]
Sorry, I'm not sure how to do that within docker since the container stops as soon as I start it.  I tried to delete the container and start from scratch but I get the same error.

**Comment by maddox** [comment]
Hmm. I'm pretty unaware about anything related to Docker, lol. Maybe when the container was built it didn't get its modules updated? Seems like they need to be built from scratch every time. But I have no idea how any of this works, lol.

**Comment by nkgilley** [comment]
I added the rm command to the dockerfile and tested and it fixed the issue for me.  Created a PR, thanks!
