### ISSUE TITLE
Error:  MAX_CLIENTS=6

### ISSUE THREAD

**Issue by wayner9** [maddox/harmony-api#75]
This shows up in my error log.  Some time recently Harmony increased the number of devices to 15 from 6.  Can this be increased?

But even at that when I click GET hubs in the web UI it shows me 6 hubs in the JSON output.  But on the web page it only lists 5 of the 5 hubs.

**Comment by wayner9** [comment]
One interesting thing to note is that I do not have this error when using harmony-api under an Ubuntu VM but I do have the error when running harmony-api as a docker in unRAID.

**Comment by wayner9** [comment]
Here is more detail on this error from the log:

`events.js:141
throw er; // Unhandled 'error' event

^

Error: MAX_CLIENTS=6

at Connection.onStanza (/usr/src/app/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:355:17)
at StreamParser.<anonymous> (/usr/src/app/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:226:10)
at emitOne (events.js:77:13)
at StreamParser.emit (events.js:169:7)
at SaxLtx.<anonymous> (/usr/src/app/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/StreamParser.js:58:14)
at emitOne (events.js:77:13)
at SaxLtx.emit (events.js:169:7)
at SaxLtx._handleTagOpening (/usr/src/app/node_modules/harmonyhubjs-client/node_modules/ltx/lib/parsers/ltx.js:31:18)
at SaxLtx.write (/usr/src/app/node_modules/harmonyhubjs-client/node_modules/ltx/lib/parsers/ltx.js:105:26)
at StreamParser.write (/usr/src/app/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/StreamParser.js:123:17)
at Connection.onData (/usr/src/app/node_modules/harmonyhubjs-client/node_modules/node-xmpp-client/node_modules/node-xmpp-core/lib/Connection.js:305:17)

npm info harmony-api@2.3.5 Failed to exec start script

npm ERR! Linux 4.9.8-unRAID
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.8.4
npm ERR! npm v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! harmony-api@2.3.5 start: `node app.js`
npm ERR! Exit status 1


npm ERR! Failed at the harmony-api@2.3.5 start script 'node app.js'.

npm ERR! This is most likely a problem with the harmony-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs harmony-api
npm ERR! Or if that isn't available, you can get their info via:


npm ERR! npm owner ls harmony-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! /usr/src/app/npm-debug.log`

But if I try to start again manually it works and this is what is in the log:
`npm info it worked if it ends with ok
npm info using npm@2.15.11
npm info using node@v4.8.4
npm info prestart harmony-api@2.3.5
npm info start harmony-api@2.3.5

> harmony-api@2.3.5 start /usr/src/app
> node app.js

Starting discovery.
Starting discovery.
Hub discovered: Office at 192.168.1.201.
Hub discovered: Bedroom at 192.168.1.202.
Hub discovered: TV Room at 192.168.1.200.`

**Comment by wayner9** [comment]
One more note:  This error is mentioned in the harmonyhubjs-client repository at:

https://github.com/swissmanu/harmonyhubjs-client/issues/34
